version: 2.1

defaults: &defaults
  working_directory: ~/bencode

executors:
  jdk8:
    docker:
      - image: clojure:temurin-8-lein-2.11.2-jammy
    <<: *defaults
  jdk11:
    docker:
      - image: clojure:temurin-11-lein-2.11.2-jammy
    <<: *defaults
  jdk17:
    docker:
      - image: clojure:temurin-17-lein-2.11.2-jammy
    <<: *defaults
  jdk21:
    docker:
      - image: clojure:temurin-21-lein-2.11.2-jammy
    <<: *defaults

jobs:
  test:
    parameters:
      jdk_version:
        description: "JDK version"
        type: string
    executor: << parameters.jdk_version >>
    steps:
      - checkout
      - restore_cache:
          key: bencode-{{ checksum "project.clj" }}
      - run:
          name: Run Tests
          command: lein test
      - save_cache:
          paths:
            - $HOME/.m2
            - $HOME/.lein
          key: bencode-{{ checksum "project.clj" }}

workflows:
  test-with-matrix:
    jobs:
      - test:
          matrix:
            parameters:
              jdk_version: ["jdk8", "jdk11", "jdk17", "jdk21"]
